# -*- coding: utf-8 -*-
"""23-1 TA

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1unC9Q9L5uF1IavKanx79hxYGaHakbRon

# 1. 출력
"""

# 9501번 연습문제 1
print("첫 번째 프로그램입니다.")

# 700번 자가진단 1
print("Python")

# 9502번 연습문제 2 ver.1
print("두 번째 프로그램입니다.\n2\n번째 프로그램입니다.")

# 9502번 연습문제 2 ver.2
print("두 번째 프로그램입니다.")
print("2")
print("번째 프로그램입니다.")

# 701번 자가진단 2-1
print("Score:")
print("100")
print("GREAT!")

# 702번 자가진단 2-2
print("My height")
print(170)
print("My weight")
print(68.6)

# 9503번 연습문제 3
print("3 번째 프로그램입니다.\n3 번째 프로그램입니다.")

# 703번 자가진단 3
print("1plus1 = Gwi yo mi")

# 9504번 연습문제 4
print("   @@ ")
print("  @  @ ")
print(" @    @ ")
print("@      @ ")
print(" @    @ ")
print("  @  @ ")
print("   @@")

# 704번 자가진단 4
print("(@) (@)")
print("(=^.^=)")
print("(-m-m-)")

# 9505번 연습문제 5
print("수식을 계산해봅시다.")
print("5 + 2")
print(7)

# 705번 자가진단 5-1
print("5 Dan")
print("5 * 2 = 10")

# 706번 자가진단 5-2
print("6 + 2 = 8")
print("6 - 2 = 4")
print("6 * 2 = 12")
print("6 / 2 = 3.0")

# 707번 형성평가 1
print("My name is Hong")

# 708번 형성평가 2
print("My hometown")
print("Flowering mountain")

# 709번 형성평가 3
print("TTTTTTTTTT")
print("TTTTTTTTTT")
print("    TT")
print("    TT")
print("    TT")

# 710번 형성평가 4
print("kor 90")
print("mat 80")
print("eng 100")
print("sum 270")

"""# 2. 변수와 입력"""

# 9506번 연습문제 1
a = 10
b = "Apple"
print(a)
print(b)

# 720번 자가진단 1
a = -100
print(a)

# 9507번 연습문제 2
a = 10
b = 20
temp = a
a = b
b = temp
print(a,b)

# 721번 자가진단 2
a, b = -1, 100

print(a)
print(b)

# 9508번 연습문제 3
a, b = 10, 20
print(a, "+", b, "=", a+b)
a, b = 30, 40
print(a, "+", b, "=", a+b)

# 722번 자가진단 3
a, b = 55, 10
print(a, "-", b, "=", a-b)
a, b = 2008, 1999
print(a, "-", b, "=", a-b)

# 9509번 연습문제 4
r, pi = 5, 3.14
circumference = 2*r*pi
area = r*r*pi
print("원주 = 5 * 2 * 3.14 =", circumference)
print("넓이 = 5 * 5 * 3.14 =", area)

# 723번 자가진단 4
weight = 49
gravity = 0.2683
print(weight, "*", gravity, "=", weight*gravity)

# 9510 연습문제 5
name = input("당신의 이름은 무엇입니까? ")

print("당신의 이름은 %s 군요." % name)

# 724 자가진단 5
school = input("School? ")

print("Your school is %s" % school)

# 9511 연습문제 6
num_1 = int(input("수를 입력하시오. "))
num_2 = int(input("수를 입력하시오. "))
print("%d + %d = %d" %(num_1,num_2,num_1+num_2))
print("%d * %d = %d" %(num_1,num_2,num_1*num_2))

# 725번 자가진단 6
num1 = int(input("Number 1? "))
num2 = int(input("Number 2? "))

print("%d * %d = %d" %(num1,num2,num1*num2))
print("{} / {} = {}".format(num1,num2,num1/num2))

# 9512번 연습문제 7
height = int(input("키를 입력하시오. "))
weight = float(input("몸무게를 입력하시오. "))
name = input("이름을 입력하시오. ")

print("키 =", height)
print("몸무게 =", weight)
print("이름 =", name)

# 726번 자가진단 7
width = float(input("Garo : "))
height = float(input("Sero : "))

print(width*height)

# 9513번 연습문제 8
a = float(input())
b = float(input())

print("x =", a)
print("y =", b)

# 727 자가진단 8
sentence1 = input()
sentence2 = input()
sentence3 = input()

print(sentence1)
print(sentence2)
print(sentence3)

# 728번 형성평가 1
a, b, c = 10,20,30
print("{} + {} = {}".format(a,b,c))

# 729번 형성평가 2
f1, f2 = 80.5, 22.34

print("%.1f %.2f %.2f" %(f1,f2,f1+f2))

# 730번 형성평가 3
f, num = 10.5, 50

print("%.1f * %d = %.1f" %(f,num,f*num))

# 731번 형성평가 4
a = int(input())
b = int(input())
c = int(input())

print("sum =", a+b+c)
print("avg =", (a+b+c)//3)

# 732번 형성평가 5
distance = float(input("yard? "))

change_cm = 91.44 * distance

print("{0} yard = {1} cm".format(distance,change_cm))

"""# 3. 연산자"""

# 9514번 연습문제 1
num1 = int(input("수를 입력하시오. "))
num2 = int(input("수를 입력하시오. "))

print("%d + %d = %d" %(num1,num2,num1+num2))
print("%d - %d = %d" % (num1,num2,num1-num2))
print("%d * %d = %d" %(num1,num2,num1*num2))
print("%d // %d = %d" %(num1,num2,num1//num2))
print("{} % {} = {}".format(num1,num2,num1%num2))
print("%d ** %d = %d" %(num1,num2,num1**num2))

# 740번 자가진단 1
a = int(input())
b = int(input())
c = int(input())
result = a+b+c
average = result // 3
print("sum :",result)
print("avg :", average)

# 9515번 연습문제 2-1
a = int(input("정수를 입력하시오. ")) + 3
b = int(input("정수를 입력하시오. ")) - 3
c = int(input("정수를 입력하시오. ")) * 3
d = int(input("정수를 입력하시오. ")) // 3
e = int(input("정수를 입력하시오. ")) % 3
f = int(input("정수를 입력하시오. ")) **3

print(a,b,c,d,e,f)

# 9516번 연습문제 2-2
a = int(input("정수를 입력하시오. ")) + 3
b = int(input("정수를 입력하시오. ")) - 3
c = int(input("정수를 입력하시오. ")) * 3
d = int(input("정수를 입력하시오. ")) // 3
e = int(input("정수를 입력하시오. ")) % 3
f = int(input("정수를 입력하시오. ")) **3

print(a,b,c,d,e,f)

# 741번 자가진단 2-1
a = int(input())

print(a)
print(a+2)

# 742번 자가진단 2-2
a = int(input()) + 100
b = int(input()) % 10

print(a,b)

# 743번 자가진단 2-3
a = int(input())
b = int(input()) -1

multi = a * b
a += 1

print(a,b,multi)

# 9517번 연습문제 3
a = int(input())
b = int(input())
c = int(input())

print(a==b, b==c,c==b,c==a)

# 744번 자가진단 3
a = int(input())
b = int(input())

print(a==b)
print(a!=b)

# 9518번 연습문제 4
a = int(input())
b = int(input())
c = int(input())

print(a>b, b>=c, a <= b, b < c)

# 745번 자가진단 4
a = int(input())
b = int(input())

print("%d > %d --- %s" %(a,b,a>b))
print("%d < %d --- %s" %(a,b,a<b))
print("%d >= %d --- %s" %(a,b,a>=b))
print("%d <= %d --- %s" %(a,b,a<=b))

# 9519번 연습문제 5
a = False
b = True
c = True

print(a and b == True, a or b == True, b and c == True, a == False)

# 746번 자가진단 5
a = True
b = True
c = False

print(not a)
print(a and b)
print(a or b)
print(a and (b or c))
print(a or (b and c))
print(not a or (b and not c))

# 9520번 연습문제 6
a = 0
b = 1
c = 2

print(a < b, b < c, a > c, a < c)

# 747번 자가진단 6
a = int(input())
b = int(input())
c = int(input())

print(a > b and a > c, a == b and a == c)

# 9521 연습문제 7
a = input()
b = input()
c = input()

print(a+b)
print(c*10)

# 748 자가진단 7
a = input()
b = input()

print(a*2+b*3)

# 749 형성평가 1
k = int(input())
e = int(input())
m = int(input())
c = int(input())
total = k+e+m+c
print("sum", total)
print("avg", total//4)

# 750번 형성평가

num1 = int(input())
num2 = int(input())

print("%d / %d = %d ... %d" % (num1,num2,num1//num2, num1%num2))

# 751번 형성평가 3
width = int(input()) + 5
height = int(input()) * 2
area = width * height

print("width =", width)
print("length =", height)
print("area =", area)

# 752번 형성평가 4

num1 = int(input()) + 1
num2 = int(input())

print(num1,num2)
print(num1, num2-1)

# 753번 형성평가 5 ver.1

brother = int(input("Brother? "))
sister = int(input("Sister? "))

if brother != sister:
  print("True")
else:
  print("False")

# 753번 형성평가 5 ver.2

brother = int(input("Brother? "))
sister = int(input("Sister? "))
answer = (brother != sister)
print(answer)

# 754번 형성평가 6 ver.1

M_height = int(input())
M_weight = int(input())
K_height = int(input())
K_weight = int(input())

answer = M_height > K_height and M_weight > K_weight
print(answer)

# 754번 형성평가 6 ver.1

M_height = int(input())
M_weight = int(input())
K_height = int(input())
K_weight = int(input())

if M_height > K_height and M_weight > K_weight:
  print("True")
else:
  print("False")

# 755번 형성평가 7
name1 = input()
name2 = input()

print(name1, "and", name2)
print(name1+"&"+name2)

# 756번 형성평가 8

st1 = input()
st2 = input()
loop = int(input())
print(st2*loop+st1)

"""# 4. 문자열1"""

# 9522번 연습문제
a,b = map(str, input().split())

print(a)
print(b)

# 761번 자가진단 1

st1, st2 = input().split()

print(st2, st1+st2)

# 9523번 연습문제 2 ver.1

a,b,c = map(int, input().split())

print("잘못된 결과 :", str(a)+str(b)+str(c))
print("올바른 결과 :", a+b+c)

# 9523번 연습문제 2 ver.2

a,b,c = map(int, input().split())

print("잘못된 결과 : %s" % (str(a)+str(b)+str(c)))
print("올바른 결과 : %d" % (a+b+c))

# 762번 자가진단 2

student_1, age_1 = input().split()
student_2, age_2 = input().split()

print("{} age + {} age = {}".format(student_1,student_2, int(age_1)+int(age_2)))

# 9524번 연습문제 3

st = input()
print(st.strip())

# 763번 자가진단 3

st1 = input().rstrip()
st2 = input().rstrip()
print(st1, st2)

# 9525번 연습문제 4

st1, st2 = input().split()

print(st1, "like", st2)
print(st1, "like", st2)
print(st1, "like", st2)
print(st1, "like", st2)

# 764번 자가진단 4

animal, animal_sound = input().split()
print(animal, "sounds", animal_sound+".")
animal, animal_sound = input().split()
print(animal, "sounds", animal_sound+".")
animal, animal_sound = input().split()
print(animal, "sounds", animal_sound+".")

# 9526번 연습문제 5

name, height, weight = input().split()

print("%s의 키는 %scm이며, 몸무게는 %.6fkg입니다." % (name, height,float(weight)))
print("%s의 키는 %scm이며, 몸무게는 %.6fkg입니다." % (name, height,float(weight)))

# 993번 자가진단 5

name = input()
age = int(input())
average = float(input())

print("I am %s(IDNo. %d). I got %.6f in my midterm exam." % (name, age, average))

# 9527번 연습문제 6

name, kor, eng, math = input().split()

print("           %s  %s  %s  %s  %s    %s" %('name', 'kor', 'eng', 'mat', 'sum', 'avg'))
print("     %s  %s  %3s  %3s  %s  %.2f" %(name,kor,eng,math,int(kor)+int(eng)+int(math),(int(kor)+int(eng)+int(math))/3))
print()
print("           %s  %s  %s  %s  %s    %s" %('name', 'kor', 'eng', 'mat', 'sum', 'avg'))
print("     %s  %s  %3s  %3s  %s  %.2f" %(name,kor,eng,math,int(kor)+int(eng)+int(math),(int(kor)+int(eng)+int(math))/3))

# 879번 자가진단 6

print("%10s %9s %9s %9s" % ("item","count","price","rate"))
print("%10s %9s %9s %9s" % ("pen",20,100,50.5))
print("%10s %9s %9s %9s" % ("note",5,95,35.3))
print("%10s %9s %9s %9s" % ("eraser",110,97,14.2))

# 9528번 연습문제 7

name, height, weight = input().split()
print("%s의 키는 %scm이며, 몸무게는 %.1fkg입니다." % (name, height,float(weight)))

# 765번 자가진단 7

a=input()
b=int(input())
c=float(input())
print("I am %s(IdNo. %d). I got %.2f in my midterm exam."%(a,b,c))

# 766번 형성평가 1

st1,st2,st3,st4 = input().split()
print(st4,st3,st2,st1)

# 767번 형성평가 2

base, upper, height = map(int, input().split())

area = (base+upper) * height / 2

print(round(area,1))

# 768번 형성평가 3

singer = input()
song = input()
print("%s: %s" %(singer, song))
singer = input()
song = input()
print("%s: %s" %(singer, song))

# 769번 형성평가 4

weight = float(input("LB? "))
kg_result = weight * 0.45
print("%.1fLB is %.1fKG." % (weight, kg_result))

# 770번 형성평가 5
name, height, weight = input().split()
print("%s의 키는 %scm이며, 몸무게는 %.1fkg입니다." % (name, height,float(weight)))

"""# 리스트1"""

# 9529번 연습문제 1

lst = [1,'noodle', -2, 'fried rice', 4.54]
print(lst)

# 781번 자가진단 1

lst = ['Salad', 'Pizza', 'Chicken', 'Soup']

print(lst)

# 9530번 연습문제 2

name_list = ['민호', '동혁', '재욱']

print(name_list[0])
print(name_list[1])
print(name_list[2])

# 782번 자가진단 2

st = ['Python', 'is', 'exciting']

print(" ".join(st))

# 9531번 연습문제 3

name_lst = ['철수', '동원', '호영']
name_list = ['영희', '이슬', '지혜']

print(name_lst + name_list)
print((name_lst + name_list) * 2)

# 783번 자가진단 3

lst = [1,2,3]
lst2 = [2,4,6]
lst3 = [3,6,9]

print(lst+lst3 *3 + lst2)

# 9532번 연습문제 4

st_list = []

st_input = input("문자열을 입력하시오: ")
st_list.append(st_input)
st_input = input("문자열을 입력하시오: ")
st_list.append(st_input)
st_input = input("문자열을 입력하시오: ")
st_list.append(st_input)

print(st_list)

# 784번 자가진단 4

sample_list = [1,2]
num = int(input())
sample_list.append(num)

print(sample_list[-1])
print(sample_list[-2])
print(sample_list[-3])

# 9533번 연습문제 5

st = list(input("String? "))

print(st)
print(st[2])

# 785번 자가진단 5

st = list(input())

print(st[0])
print(st[2])

# 9534번 연습문제 6

sample = ['Carrot', 'Onion', 'Cabbage', 'Potato', 'Sweet Potato', 'Bean']


print("첫 번째 원소:", sample[0])
print("마지막 원소:", sample[-1])
print("리스트 거꾸로 출력하기:", sample[::-1])
print("li[2:5]:", sample[2:5])
print("li[5:2:-1]:", sample[5:2:-1])
print("li[1:6:2]:", sample[1:6:2])

# 786번 자가진단 6-1

data = []

data.append(input("Element? "))
data.append(input("Element? "))
data.append(input("Element? "))
data.append(input("Element? "))
data.append(input("Element? "))
data.append(input("Element? "))

search = int(input("Index? "))

print(data[search:])

# 787번 자가진단 6-2

data = []

data.append(input("Element? "))
data.append(input("Element? "))
data.insert(1,input("Element? "))
data.append(input("Element? "))
data.insert(2,input("Element? "))
data.append(input("Element? "))

print(data)

# 788번 자가진단 6-3

lst = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]
increase = int(input())
print(lst[increase-1::increase])

# 9535번 연습문제 7

lst = list(map(str, input().split()))
print(lst)

# 789번 자가진단 7

data = list(map(str, input().split()))
print(data[::-1])

# 790번 형성평가 1

data = [-1, -2, -3, -4, -5]

print(data)

# 791번 형성평가 2

lst = []
a, b = map(int, input().split())
c, d = map(int, input().split())

for i in range(b):
  lst.append(a)
for i in range(d):
  lst.append(c)

print(lst)

# 792번 형성평가 3

color_lst, animal_lst = [], []
color, animal = map(str, input("Input? ").split())
color_lst.append(color), animal_lst.append(animal)
color, animal = map(str, input("Input? ").split())
color_lst.append(color), animal_lst.append(animal)
color, animal = map(str, input("Input? ").split())
color_lst.append(color), animal_lst.append(animal)
color, animal = map(str, input("Input? ").split())
color_lst.append(color), animal_lst.append(animal)
print("Color:", color_lst)
print("Animal:", animal_lst)

# 793번 형성평가 4

st = list(input())
print(st[::-1])

# 794번 형성평가 5

data = list(map(str, input().split()))
print(data[2::3])

# 795번 형성평가 6

data = list(map(str, input().split()))

print(data[len(data)-2:0:-1])